# vim:set sw=8 nosta:

BINS=
SUBDIRS=


all:

install:
	$(INSTALL_DIR) $(PREFIX)/hotplug2/etc
	$(INSTALL) hotplug2.rules-2.6kernel $(PREFIX)/hotplug2/etc/hotplug2.rules

include ../common.mak
MAKEDEP:=
